apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumba-web-deployment
  labels:
    app: lumba-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lumba-web
  template:
    metadata:
      labels:
        app: lumba-web
    spec:
      containers:
        - name: lumba-web
          image: gbhisma/lumba-web
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: lumba-web
          envFrom:
            - secretRef:
                name: lumba-secret
          env:
            - name: NEXT_PUBLIC_NODE_ENV
              value: DEVELOPMENT
            - name: NEXT_PUBLIC_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: lumba-web-config
                  key: web-url
            - name: NEXT_PUBLIC_API_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: lumba-api-config
                  key: api-url
---
apiVersion: v1
kind: Service
metadata:
  name: lumba-web-service
spec:
  type: LoadBalancer
  selector:
    app: lumba-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: lumba-web
