apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      name: celery-flower
  template:
    metadata:
      labels:
        name: celery-flower
    spec:
      containers:
        - name: celery-flower
          image: gbhisma/lumba-model
          ports:
            - containerPort: 5555
              name: lumba-flower
          command:
            - "bash"
            - "-c"
            - "celery -A modeling flower -l info --persistent=True"
          env:
            - name: BACKEND_API_URL
              valueFrom:
                configMapKeyRef:
                  name: lumba-api-config
                  key: api-url
            - name: REDIS_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: lumba-secret
                  key: REDIS_ENDPOINT_URL
---
apiVersion: v1
kind: Service
metadata:
  name: lumba-flower-service
spec:
  type: LoadBalancer
  selector:
    app: lumba-flower
  ports:
    - protocol: TCP
      port: 5555
      targetPort: lumba-flower
