apiVersion: apps/v1
kind: Deployment
metadata:
  name: lumba-worker-xgboost
spec:
  replicas: 1
  selector:
    matchLabels:
      name: lumba-worker-xgboost
  template:
    metadata:
      labels:
        name: lumba-worker-xgboost
    spec:
      containers:
        - name: lumba-worker-xgboost
          image: gbhisma/lumba-model
          imagePullPolicy: Always
          command:
            - "bash"
            - "-c"
            - "python3 manage.py rqworker xgboost"
          envFrom:
            - secretRef:
                name: lumba-secret
          env:
            - name: REDIS_QUEUE_DEFAULT
              value: '7'
            - name: REDIS_QUEUE_XGBOOST
              value: '8'
            - name: BACKEND_API_URL
              valueFrom:
                configMapKeyRef:
                  name: lumba-api-config
                  key: api-url
            - name: REDIS_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: lumba-secret
                  key: REDIS_ENDPOINT_URL
